# Generated by Django 4.2.5 on 2026-06-14 12:13

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('initials', models.CharField(help_text="2–3 letter avatar initials e.g. 'AK'", max_length=3)),
                ('whatsapp_number', models.CharField(help_text="International format without '+', e.g. 233200000001", max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('min_deposit', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('max_deposit', models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=10)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Agent fee as a percentage e.g. 1.50 means 1.5%', max_digits=5)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))])),
                ('avg_speed_minutes', models.PositiveSmallIntegerField(default=10, help_text='Average confirmation time in minutes')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('busy', 'Busy')], default='online', max_length=10)),
                ('avatar_color', models.CharField(default='#fef0ec', help_text='CSS hex background colour for the avatar', max_length=7)),
                ('avatar_text_color', models.CharField(default='#e85d35', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['-status', '-total_trades'],
            },
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('min_trade', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_trade', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('volatility', models.DecimalField(decimal_places=2, default=0.19, max_digits=5)),
                ('pip_size', models.DecimalField(decimal_places=4, default=0.01, max_digits=6)),
                ('tick_speed', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('demo_balance', models.DecimalField(decimal_places=2, default=10000.0, max_digits=12)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_type', models.CharField(choices=[('RISE_FALL', 'Rise / Fall'), ('OVER_UNDER', 'Over / Under'), ('ACCUMULATOR', 'Accumulator')], max_length=20)),
                ('direction', models.CharField(choices=[('RISE', 'Rise'), ('FALL', 'Fall'), ('OVER', 'Over'), ('UNDER', 'Under'), ('ACCUM', 'Accumulator')], max_length=10)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_pct', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barrier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration', models.IntegerField(choices=[(1, '1 tick'), (5, '5 ticks'), (10, '10 ticks'), (60, '1 min'), (300, '5 min'), (900, '15 min')])),
                ('duration_unit', models.CharField(default='ticks', max_length=10)),
                ('ticks_elapsed', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('WON', 'Won'), ('LOST', 'Lost'), ('EXPIRED', 'Expired')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('house_edge', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HouseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_pct', models.DecimalField(decimal_places=2, default=85.0, max_digits=5)),
                ('house_edge', models.DecimalField(decimal_places=2, default=15.0, max_digits=5)),
                ('favourability', models.IntegerField(default=50, help_text='0-100. 50=fair, >50=user favoured, <50=house favoured')),
                ('max_stake', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('min_stake', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('pair', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='house_settings', to='dashboard.tradingpair')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], default='deposit', max_length=20)),
                ('method', models.CharField(choices=[('agent', 'Agent (P2P)'), ('crypto_btc', 'Bitcoin (BTC)'), ('crypto_usdt', 'USDT TRC20'), ('crypto_eth', 'Ethereum (ETH)'), ('bank', 'Bank Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))])),
                ('fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='amount minus fee — what is credited to the user', max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('crypto_address', models.CharField(blank=True, default='', max_length=200)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=200, verbose_name='Transaction Hash / TxID')),
                ('proof_screenshot', models.ImageField(blank=True, null=True, upload_to='deposits/proofs/%Y/%m/')),
                ('reference', models.CharField(editable=False, max_length=60, unique=True)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, help_text='Populated only for agent-based deposits', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='dashboard.agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='dashboard_t_user_id_622ff6_idx'), models.Index(fields=['status'], name='dashboard_t_status_7b0a67_idx'), models.Index(fields=['tx_hash'], name='dashboard_t_tx_hash_5be0de_idx')],
            },
        ),
        migrations.CreateModel(
            name='PriceTick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticks', to='dashboard.tradingpair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['pair', '-timestamp'], name='dashboard_p_pair_id_d33f4b_idx')],
            },
        ),
    ]
