# Generated by Django 4.2.5 on 2026-06-15 13:00

import apps.dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.dashboard.models.generate_bot_key, max_length=16, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Key',
                'verbose_name_plural': 'Bot Keys',
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake_per_trade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timeframe', models.PositiveIntegerField(choices=[(5, '5 Minutes'), (10, '10 Minutes'), (20, '20 Minutes'), (30, '30 Minutes')], default=5)),
                ('is_demo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('outcome', models.CharField(choices=[('PROFIT', 'Profit'), ('BREAKEVEN', 'Breakeven'), ('LOSS', 'Loss'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('house_outcome', models.CharField(default='PROFIT', max_length=10)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('trades_won', models.PositiveIntegerField(default=0)),
                ('trades_lost', models.PositiveIntegerField(default=0)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bot_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='dashboard.botkey')),
            ],
            options={
                'verbose_name': 'Bot Session',
                'verbose_name_plural': 'Bot Sessions',
            },
        ),
        migrations.CreateModel(
            name='BotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bot_type', models.CharField(choices=[('RISE_FALL', 'Rise / Fall'), ('OVER_UNDER', 'Over / Under'), ('ACCUMULATOR', 'Accumulator')], max_length=20)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('trades_per_5min', models.PositiveIntegerField(default=5)),
                ('base_win_rate', models.PositiveIntegerField(default=55)),
                ('profit_pct', models.DecimalField(decimal_places=2, default=15.63, max_digits=5)),
                ('house_outcome', models.CharField(choices=[('PROFIT', 'Profit'), ('BREAKEVEN', 'Breakeven'), ('LOSS', 'Loss')], default='PROFIT', max_length=10)),
                ('breakeven_min_pct', models.DecimalField(decimal_places=2, default=-2.0, max_digits=5)),
                ('breakeven_max_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bot Template',
                'verbose_name_plural': 'Bot Templates',
            },
        ),
        migrations.AlterField(
            model_name='housesettings',
            name='payout_pct',
            field=models.DecimalField(decimal_places=2, default=43.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='pricetick',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='trade',
            name='payout_pct',
            field=models.DecimalField(decimal_places=2, default=43.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='max_trade',
            field=models.DecimalField(decimal_places=4, default=1000.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tradingpair',
            name='min_trade',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.PositiveIntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_trades', to='dashboard.botsession')),
            ],
            options={
                'verbose_name': 'Bot Trade',
                'verbose_name_plural': 'Bot Trades',
                'ordering': ['trade_number'],
            },
        ),
        migrations.AddField(
            model_name='botsession',
            name='pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to='dashboard.tradingpair'),
        ),
        migrations.AddField(
            model_name='botsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='botkey',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keys', to='dashboard.bottemplate'),
        ),
    ]
