# Generated by Django 4.2.5 on 2026-06-16 09:25

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_botkey_botsession_bottemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Agent's current spendable balance", max_digits=12),
        ),
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, help_text='The Django user account this agent logs in with', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
