# Generated by Django 4.2.5 on 2026-06-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_transaction_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
