# Generated by Django 4.2.5 on 2026-06-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_todayrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottemplate',
            name='demo_base_win_rate',
            field=models.PositiveIntegerField(default=65),
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='demo_breakeven_max_pct',
            field=models.DecimalField(decimal_places=2, default=8.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='demo_breakeven_min_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='bottemplate',
            name='demo_house_outcome',
            field=models.CharField(choices=[('PROFIT', 'Profit'), ('BREAKEVEN', 'Breakeven'), ('LOSS', 'Loss')], default='PROFIT', max_length=10),
        ),
    ]
