# Generated by Django 4.2.5 on 2026-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bottemplate_demo_base_win_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecivingCryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(choices=[('BTC', 'BTC'), ('USDT', 'USDT'), ('ETH', 'ETH')], max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
    ]
