# Generated by Django 4.2.5 on 2026-06-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_recivingcryptowallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottemplate',
            name='users_sets',
            field=models.CharField(default='set 1', max_length=20),
        ),
    ]
