# Generated by Django 6.0.6 on 2026-06-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_bottemplate_users_sets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botkey',
            name='template',
        ),
        migrations.RemoveField(
            model_name='botsession',
            name='bot_key',
        ),
        migrations.RemoveField(
            model_name='botsession',
            name='pair',
        ),
        migrations.RemoveField(
            model_name='botsession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bottrade',
            name='session',
        ),
        migrations.DeleteModel(
            name='BotTemplate',
        ),
        migrations.DeleteModel(
            name='BotKey',
        ),
        migrations.DeleteModel(
            name='BotSession',
        ),
        migrations.DeleteModel(
            name='BotTrade',
        ),
    ]
