# Generated by Django 6.0.6 on 2026-06-26 08:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_referral_referraldeposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_market_cap', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text="The liquidity target you're aiming to maintain across the platform.", max_digits=14)),
                ('safety_threshold_pct', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Flag agents whose float drops below this % of their average float.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platform Settings',
                'verbose_name_plural': 'Platform Settings',
            },
        ),
    ]
