# Generated by Django 6.0.6 on 2026-06-28 15:00

import apps.bot.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0009_remove_botkey_template_remove_botsession_bot_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=apps.bot.models.generate_bot_key, max_length=16, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot_type', models.CharField(choices=[('RISE_FALL', 'Rise / Fall'), ('OVER_UNDER', 'Over / Under'), ('ACCUMULATOR', 'Accumulator')], max_length=20)),
                ('base_win_rate', models.PositiveIntegerField(default=55)),
                ('profit_pct', models.DecimalField(decimal_places=2, default=15.63, max_digits=5)),
                ('house_outcome', models.CharField(choices=[('PROFIT', 'Profit'), ('BREAKEVEN', 'Breakeven'), ('LOSS', 'Loss')], default='PROFIT', max_length=10)),
                ('breakeven_min_pct', models.DecimalField(decimal_places=2, default=-2.0, max_digits=5)),
                ('breakeven_max_pct', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('demo_base_win_rate', models.PositiveIntegerField(default=65)),
                ('demo_house_outcome', models.CharField(choices=[('PROFIT', 'Profit'), ('BREAKEVEN', 'Breakeven'), ('LOSS', 'Loss')], default='PROFIT', max_length=10)),
                ('demo_breakeven_min_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('demo_breakeven_max_pct', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bot Key',
                'verbose_name_plural': 'Bot Keys',
            },
        ),
        migrations.CreateModel(
            name='BotTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timeframe', models.PositiveIntegerField(choices=[(10, '10 Minutes'), (20, '20 Minutes'), (30, '30 Minutes')], default=5)),
                ('trade_per_5min', models.PositiveIntegerField(default=1)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=10)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botkey', to='bot.botkey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='botemplate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bot Template',
                'verbose_name_plural': 'Bot Templates',
            },
        ),
        migrations.CreateModel(
            name='BotSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stake_per_trade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_demo', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('outcome', models.CharField(choices=[('PROFIT', 'Profit'), ('BREAKEVEN', 'Breakeven'), ('LOSS', 'Loss'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('house_outcome', models.CharField(default='PROFIT', max_length=10)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('trades_won', models.PositiveIntegerField(default=0)),
                ('trades_lost', models.PositiveIntegerField(default=0)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_loss', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_pnl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('bot_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='bot.botkey')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_pair', to='dashboard.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_sessions', to=settings.AUTH_USER_MODEL)),
                ('bot_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_template', to='bot.bottemplate')),
            ],
            options={
                'verbose_name': 'Bot Session',
                'verbose_name_plural': 'Bot Sessions',
            },
        ),
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_number', models.PositiveIntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exit_price', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('stake', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('result', models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_trades', to='bot.botsession')),
            ],
            options={
                'verbose_name': 'Bot Trade',
                'verbose_name_plural': 'Bot Trades',
                'ordering': ['trade_number'],
            },
        ),
    ]
