# Generated by Django 6.0.6 on 2026-06-29 16:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='base_win_rate',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='botsession',
            name='breakeven_max_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='botsession',
            name='breakeven_min_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('-2.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='botsession',
            name='profit_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.63'), max_digits=5),
        ),
    ]
