# Generated by Django 6.0.6 on 2026-06-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_botsession_base_win_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsession',
            name='timeframe',
            field=models.PositiveIntegerField(choices=[(10, '10 Minutes'), (20, '20 Minutes'), (30, '30 Minutes')], default=5),
        ),
        migrations.AddField(
            model_name='botsession',
            name='trade_per_5min',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
