# Generated by Django 6.0.6 on 2026-06-30 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_botsession_timeframe_botsession_trade_per_5min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsession',
            name='bot_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='bot.bottemplate'),
        ),
    ]
